# Schema for the configuration files of the stanford_syndication module.
stanford_syndication.settings:
  type: config_object
  label: Syndication settings
  mapping:
    enabled:
      type: boolean
      label: Enable the syndication connection.
    syndicators:
      type: sequence
      label: Syndicators settings.
